services:
  db:
    image: nafama/sqlpinacoteca:v1
    container_name: sqlpinacoteca
    environment:
      MYSQL_ROOT_PASSWORD: pinacoteca1234
      MYSQL_DATABASE: pinacoteca
      MYSQL_USER: davinci
      MYSQL_PASSWORD: davinci1234
    ports:
      - "3308:3306"
  php:
    image: nafama/pinacoteca:v1
    container_name: phppinacoteca
    ports:
      - "8082:80"
    depends_on:
      - db
