services:
  db:
    image: nafama/mi_pinacoteca:v1
    container_name: MysqlEx2
    environment:
      MYSQL_ROOT_PASSWORD: pinacoteca1234
      MYSQL_DATABASE: pinacoteca
      MYSQL_USER: davinci
      MYSQL_PASSWORD: davinci1234
    ports:
      - "3308:3306"
  php:
    image: nafama/mi_app_pinacoteca:v1
    container_name: phpEx2
    ports:
      - "8082:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpAdminEx2
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pinacoteca1234
    ports:
      - "8081:80"
    depends_on:
      - db